# Generated by Django 3.2.6 on 2021-08-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume_model',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
